package utils

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func FindJarFile() (string, error) {
	files, err := filepath.Glob("paper-*.jar")
	if err != nil {
		return "", err
	}

	for _, file := range files {
		if info, err := os.Stat(file); err == nil && !info.IsDir() {
			return file, nil
		}
	}

	return "", nil
}

func HandleEULA() error {
	eulaFile := "eula.txt"
	
	if data, err := os.ReadFile(eulaFile); err == nil {
		content := string(data)
		if strings.Contains(content, "eula=true") {
			return nil
		}
	}

	eulaContent := `# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
# Generated by minecraft-server-launcher
eula=true
`

	if err := os.WriteFile(eulaFile, []byte(eulaContent), 0644); err != nil {
		return fmt.Errorf("failed to write eula.txt: %w", err)
	}

	fmt.Println("Accepted Minecraft EULA")
	return nil
}

func Pause() {
	fmt.Print("\nPress Enter to exit...")
	bufio.NewReader(os.Stdin).ReadBytes('\n')
}
