package utils

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/nevcea-sub/minecraft-server-launcher/internal/logger"
)

func parseJarFileName(filename string) (version string, build int, ok bool) {
	name := filename[6 : len(filename)-4]
	lastDash := strings.LastIndex(name, "-")
	if lastDash < 0 {
		return "", 0, false
	}

	version = name[:lastDash]
	buildStr := name[lastDash+1:]
	build, err := strconv.Atoi(buildStr)
	if err != nil {
		return "", 0, false
	}

	return version, build, true
}

func FindJarFile() (string, error) {
	files, err := filepath.Glob("paper-*.jar")
	if err != nil {
		return "", fmt.Errorf("failed to search for JAR files: %w", err)
	}

	if len(files) == 0 {
		return "", nil
	}

	type jarInfo struct {
		path    string
		build   int
		modTime int64
	}

	jars := make([]jarInfo, 0, len(files))

	for _, file := range files {
		info, err := os.Stat(file)
		if err != nil || info.IsDir() {
			continue
		}

		baseName := filepath.Base(file)
		_, build, _ := parseJarFileName(baseName)
		jars = append(jars, jarInfo{
			path:    file,
			build:   build,
			modTime: info.ModTime().Unix(),
		})
	}

	if len(jars) == 0 {
		return "", nil
	}

	sort.Slice(jars, func(i, j int) bool {
		if jars[i].build != jars[j].build {
			return jars[i].build > jars[j].build
		}
		return jars[i].modTime > jars[j].modTime
	})

	return jars[0].path, nil
}

func HandleEULA() error {
	eulaFile := "eula.txt"

	data, err := os.ReadFile(eulaFile)
	if err == nil {
		if strings.Contains(string(data), "eula=true") {
			return nil
		}
	}

	eulaContent := `# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
# Generated by minecraft-server-launcher
eula=true
`

	if err := os.WriteFile(eulaFile, []byte(eulaContent), 0644); err != nil {
		return fmt.Errorf("failed to write eula.txt: %w", err)
	}

	logger.Info("Automatically accepted Minecraft EULA")
	return nil
}

func Pause() {
	fmt.Print("\nPress Enter to exit...")
	reader := bufio.NewReader(os.Stdin)
	if _, err := reader.ReadBytes('\n'); err != nil {
		_ = err
	}
}
